server {
    listen 80;
    server_name localhost;
    absolute_redirect off;
    resolver 127.0.0.11 ipv6=off;

    location = / {
        return 302 /redis-movies-searcher/;
    }

    location /redis-movies-searcher {
        alias /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    location /search {
        set $search_upstream "http://workspace:8081";
        proxy_pass $search_upstream;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
